#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you wrote.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "dsh local service setup"

DSH_ENV="$HOME/.dsh/.env"
DSH_HOME="$HOME/.local/share/im-bridge/dsh"
DSH_SUPERVISOR="$DSH_HOME/supervisor.mjs"
DSH_AGENTS_HOME="$HOME/.dsh/empty-agents"
LOG_DIR="$HOME/Library/Logs/im-bridge"
LOG_FILE="$LOG_DIR/dsh.log"
PLIST="$HOME/Library/LaunchAgents/dev.im-bridge.dsh.plist"
LABEL="dev.im-bridge.dsh"
DOMAIN="gui/$(id -u)"
BACKUP_DIR=""
PREVIOUS_DSH_VERSION=""
SERVICE_WAS_LOADED=0
FILES_REPLACED=0
PACKAGE_REPLACED=0
TRANSACTION_STARTED=0

rollback() {
  local status=$?
  (( status == 0 || TRANSACTION_STARTED == 0 )) && return 0
  launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true
  if (( PACKAGE_REPLACED == 1 )); then
    if [[ -n "$PREVIOUS_DSH_VERSION" ]]; then
      pnpm add -g "@deepseek-ai/dsh@$PREVIOUS_DSH_VERSION" >/dev/null 2>&1 || true
    else
      pnpm remove -g @deepseek-ai/dsh >/dev/null 2>&1 || true
    fi
  fi
  if (( FILES_REPLACED == 1 )); then
    if [[ -n "$BACKUP_DIR" && -f "$BACKUP_DIR/supervisor.mjs" ]]; then
      cp "$BACKUP_DIR/supervisor.mjs" "$DSH_SUPERVISOR"
    else
      rm -f "$DSH_SUPERVISOR"
    fi
    if [[ -n "$BACKUP_DIR" && -f "$BACKUP_DIR/dsh.plist" ]]; then
      cp "$BACKUP_DIR/dsh.plist" "$PLIST"
    else
      rm -f "$PLIST"
    fi
  fi
  if (( SERVICE_WAS_LOADED == 1 )) && [[ -f "$PLIST" ]]; then
    launchctl bootstrap "$DOMAIN" "$PLIST" >/dev/null 2>&1 || true
  fi
  # Staged files this run created but never moved into place.
  [[ -z "${SUPERVISOR_RESERVED:-}" ]] || rm -f "$SUPERVISOR_RESERVED"
  [[ -z "${SUPERVISOR_TMP:-}" ]] || rm -f "$SUPERVISOR_TMP"
  [[ -z "${PLIST_TMP:-}" ]] || rm -f "$PLIST_TMP"
  [[ -z "$BACKUP_DIR" ]] || rm -rf "$BACKUP_DIR"
  warn "setup failed; previous files, package version, and service were restored when available"
}
trap rollback EXIT

stage "Pre-flight checks"
say "This verifies local requirements without reading or printing your API key."
[[ "$(uname -s)" == "Darwin" ]] || { warn "this wizard requires macOS"; exit 1; }
[[ -t 0 ]] || { warn "run this wizard from an interactive terminal"; exit 1; }
for command in node npm pnpm launchctl lsof curl plutil; do
  command -v "$command" >/dev/null 2>&1 || { warn "$command is missing"; exit 1; }
done
NODE_BIN=$(command -v node)
NODE_DIR=$(dirname "$NODE_BIN")
NODE_MAJOR=$("$NODE_BIN" -p 'Number(process.versions.node.split(".")[0])')
(( NODE_MAJOR >= 24 )) || { warn "Node.js 24 or newer is required"; exit 1; }
[[ "$(pnpm --version)" == "11.21.0" ]] || { warn "pnpm 11.21.0 is required by this repository"; exit 1; }
[[ -f "$DSH_ENV" ]] || { warn "$DSH_ENV does not exist"; exit 1; }
[[ "$(stat -f '%Lp' "$DSH_ENV")" == "600" ]] || { warn "$DSH_ENV must have mode 600"; exit 1; }
awk '
  /^[[:space:]]*(#|$)/ { next }
  /^DEEPSEEK_API_KEY=[^[:space:]]+$/ { valid += 1; next }
  { invalid += 1 }
  END { exit !(valid == 1 && invalid == 0) }
' "$DSH_ENV" || {
  warn "$DSH_ENV must contain one non-empty DEEPSEEK_API_KEY plus comments and blank lines"
  exit 1
}
if launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1; then
  SERVICE_WAS_LOADED=1
fi
if LISTENER_PID=$(lsof -nP -t -a -iTCP@127.0.0.1:3080 -sTCP:LISTEN 2>/dev/null | head -n1) && [[ -n "$LISTENER_PID" ]]; then
  SERVICE_PID=$(launchctl print "$DOMAIN/$LABEL" 2>/dev/null | awk '/^[[:space:]]*pid = / { print $3; exit }')
  PARENT_PID=$(ps -o ppid= -p "$LISTENER_PID" | tr -d ' ')
  if [[ -n "$SERVICE_PID" && "$SERVICE_PID" == "$PARENT_PID" ]]; then
    note "The existing $LABEL child owns port 3080 and will be replaced."
  else
    warn "TCP port 3080 is used by a process outside $LABEL"
    exit 1
  fi
fi
note "Node $("$NODE_BIN" --version), pnpm $(pnpm --version), credential file mode 600."
pause "Pre-flight checks passed. Press Enter to continue."

stage "Select dsh version"
say "The registry candidate is shown now; installation occurs after local files validate."
DSH_VERSION=$(npm view @deepseek-ai/dsh version)
[[ "$DSH_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][0-9A-Za-z.-]+)?$ ]] || {
  warn "npm returned an invalid version: $DSH_VERSION"
  exit 1
}
note "Candidate: @deepseek-ai/dsh@$DSH_VERSION"
[[ "$DSH_VERSION" != *-* ]] || warn "This candidate is a prerelease."
confirm "Use this exact version for the service?" || exit 1
PREVIOUS_DSH_VERSION=$(pnpm list -g @deepseek-ai/dsh --depth 0 --json 2>/dev/null | "$NODE_BIN" -e '
let input="";
process.stdin.on("data", chunk => input += chunk);
process.stdin.on("end", () => {
  try {
    const report = JSON.parse(input);
    const root = Array.isArray(report) ? report[0] : report;
    process.stdout.write(root.dependencies?.["@deepseek-ai/dsh"]?.version ?? "");
  } catch {}
});
')
note "Selected @deepseek-ai/dsh@$DSH_VERSION."
pause "Version selected. Press Enter to continue."

stage "Create service files"
say "A single supervisor strictly parses credentials, owns logging, and propagates dsh failures."
mkdir -p "$DSH_HOME" "$DSH_AGENTS_HOME" "$LOG_DIR" "$HOME/Library/LaunchAgents"
chmod 700 "$DSH_HOME" "$DSH_AGENTS_HOME"
BACKUP_DIR=$(mktemp -d)
TRANSACTION_STARTED=1
[[ ! -f "$DSH_SUPERVISOR" ]] || cp "$DSH_SUPERVISOR" "$BACKUP_DIR/supervisor.mjs"
[[ ! -f "$PLIST" ]] || cp "$PLIST" "$BACKUP_DIR/dsh.plist"
# Node 24 selects the module loader from the final extension, so the temp file
# must still end in .mjs or --check fails with ERR_UNKNOWN_FILE_EXTENSION. BSD
# mktemp only expands XXXXXX at the end of a template, so claim the name
# exclusively first, then move it back under the .mjs extension.
SUPERVISOR_RESERVED=$(mktemp "${DSH_SUPERVISOR}.XXXXXX")
SUPERVISOR_TMP="${SUPERVISOR_RESERVED}.mjs"
mv "$SUPERVISOR_RESERVED" "$SUPERVISOR_TMP"
cat > "$SUPERVISOR_TMP" <<EOF
import {
  basename,
  dirname,
  closeSync,
  existsSync,
  openSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  statSync,
  writeSync,
} from "node:fs";
import { spawn } from "node:child_process";

const envFile = "$DSH_ENV";
const envMode = statSync(envFile).mode & 0o777;
if (envMode !== 0o600) throw new Error("dsh env must have mode 600");
const logFile = "$LOG_FILE";
const maxBytes = 10485760;
const fileCount = 5;
const lines = readFileSync(envFile, "utf8")
  .split(/\\r?\\n/)
  .filter(line => !/^\\s*(#|$)/.test(line));
if (lines.length !== 1) throw new Error("dsh env must contain only DEEPSEEK_API_KEY");
const match = /^DEEPSEEK_API_KEY=([^\\s]+)$/.exec(lines[0]);
if (!match) throw new Error("invalid or empty DEEPSEEK_API_KEY");

let fd;
let size;
function openLog() {
  fd = openSync(logFile, "a", 0o600);
  size = statSync(logFile).size;
}
function rotate() {
  closeSync(fd);
  rmSync(logFile + "." + (fileCount - 1), { force: true });
  for (let n = fileCount - 2; n >= 1; n -= 1) {
    if (existsSync(logFile + "." + n)) renameSync(logFile + "." + n, logFile + "." + (n + 1));
  }
  if (existsSync(logFile)) renameSync(logFile, logFile + ".1");
  openLog();
}
function writeChunk(chunk) {
  let offset = 0;
  while (offset < chunk.length) {
    if (size >= maxBytes) rotate();
    const length = Math.min(maxBytes - size, chunk.length - offset);
    writeSync(fd, chunk, offset, length);
    size += length;
    offset += length;
  }
}
if (existsSync(logFile) && statSync(logFile).size > maxBytes) {
  const oldContent = readFileSync(logFile);
  rmSync(logFile);
  openLog();
  writeChunk(oldContent);
} else {
  openLog();
}
for (const name of readdirSync(dirname(logFile))) {
  const prefix = basename(logFile) + ".";
  if (!name.startsWith(prefix)) continue;
  const number = Number(name.slice(prefix.length));
  if (Number.isInteger(number) && number >= fileCount) rmSync(dirname(logFile) + "/" + name);
}
for (let n = 1; n < fileCount; n += 1) {
  const archive = logFile + "." + n;
  if (existsSync(archive) && statSync(archive).size > maxBytes) {
    const content = readFileSync(archive);
    const archiveFd = openSync(archive, "w", 0o600);
    writeSync(archiveFd, content.subarray(content.length - maxBytes));
    closeSync(archiveFd);
  }
}

const child = spawn("$(pnpm bin -g)/dsh", ["web", "--no-open", "--port", "3080"], {
  cwd: "$HOME",
  env: {
    ...process.env,
    PATH: "$NODE_DIR:/usr/bin:/bin:/usr/sbin:/sbin",
    DEEPSEEK_API_KEY: match[1],
    DSH_AGENTS_HOME: "$DSH_AGENTS_HOME",
  },
  stdio: ["ignore", "pipe", "pipe"],
});
child.stdout.on("data", writeChunk);
child.stderr.on("data", writeChunk);
let stopping = false;
for (const signal of ["SIGTERM", "SIGINT"]) {
  process.on(signal, () => {
    stopping = true;
    child.kill(signal);
  });
}
child.on("error", error => {
  writeChunk(Buffer.from("dsh spawn failed: " + error.message + "\\n"));
  closeSync(fd);
  process.exit(1);
});
child.on("exit", code => {
  closeSync(fd);
  process.exit(stopping ? 0 : (code ?? 1));
});
EOF
chmod 700 "$SUPERVISOR_TMP"
"$NODE_BIN" --check "$SUPERVISOR_TMP"

PLIST_TMP=$(mktemp "${PLIST}.XXXXXX")
cat > "$PLIST_TMP" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$NODE_BIN</string>
    <string>$DSH_SUPERVISOR</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
</dict>
</plist>
EOF
chmod 600 "$PLIST_TMP"
plutil -lint "$PLIST_TMP" >/dev/null
FILES_REPLACED=1
mv "$SUPERVISOR_TMP" "$DSH_SUPERVISOR"
mv "$PLIST_TMP" "$PLIST"
note "Created credential-safe service files with bounded 10 MB x 5 logs."
pause "Service files validated. Press Enter to install dsh."

stage "Install pinned dsh"
say "The selected exact version is installed globally; failures restore the previous version."
pnpm add -g "@deepseek-ai/dsh@$DSH_VERSION"
PACKAGE_REPLACED=1
DSH_BIN=$(pnpm bin -g)/dsh
[[ -x "$DSH_BIN" ]] || { warn "dsh executable was not installed at $DSH_BIN"; exit 1; }
INSTALLED_VERSION=$(pnpm list -g @deepseek-ai/dsh --depth 0 --json | "$NODE_BIN" -e '
let input="";
process.stdin.on("data", chunk => input += chunk);
process.stdin.on("end", () => {
  const report = JSON.parse(input);
  const root = Array.isArray(report) ? report[0] : report;
  const dependency = root.dependencies?.["@deepseek-ai/dsh"];
  if (!dependency?.version) process.exit(1);
  process.stdout.write(dependency.version);
});
')
[[ "$INSTALLED_VERSION" == "$DSH_VERSION" ]] || { warn "installed version mismatch"; exit 1; }
note "Installed @deepseek-ai/dsh@$INSTALLED_VERSION."
pause "Installation verified. Press Enter to load the service."

stage "Start and verify dsh"
say "This replaces the loaded copy and verifies the supervisor child and HTTP response."
launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true
launchctl bootstrap "$DOMAIN" "$PLIST"
launchctl kickstart -k "$DOMAIN/$LABEL"
for _ in {1..30}; do
  SERVICE_PID=$(launchctl print "$DOMAIN/$LABEL" 2>/dev/null | awk '/^[[:space:]]*pid = / { print $3; exit }')
  LISTENER_PID=$(lsof -nP -t -a -iTCP@127.0.0.1:3080 -sTCP:LISTEN 2>/dev/null | head -n1 || true)
  PARENT_PID=$([[ -n "$LISTENER_PID" ]] && ps -o ppid= -p "$LISTENER_PID" | tr -d ' ' || true)
  [[ -n "$SERVICE_PID" && "$SERVICE_PID" == "$PARENT_PID" ]] && break
  sleep 1
done
[[ -n "${SERVICE_PID:-}" && "$SERVICE_PID" == "${PARENT_PID:-}" ]] || {
  warn "the LaunchAgent child did not become the port 3080 listener; inspect $LOG_FILE"
  exit 1
}
curl --fail --silent --show-error --max-time 5 "http://127.0.0.1:3080/" >/dev/null || {
  warn "dsh did not answer the root HTTP check; inspect $LOG_FILE"
  exit 1
}
FILES_REPLACED=0
PACKAGE_REPLACED=0
TRANSACTION_STARTED=0
trap - EXIT
note "dsh child PID $LISTENER_PID is listening and responding on 127.0.0.1:3080."
note "LaunchAgent $LABEL is loaded and will start at the next user login."
finish
