#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you wrote.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "im-bridge service setup"

# The pinned runtime is this checkout: the LaunchAgent runs the very files that
# were typechecked and tested here, so there is no second copy to drift.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
BRIDGE_DIR="$PROJECT_DIR/packages/bridge"
BRIDGE_ENTRY="$BRIDGE_DIR/src/index.ts"
CONFIG_DIR="$HOME/.config/im-bridge"
CONFIG_FILE="$CONFIG_DIR/config.json"
CONFIG_TMP="$CONFIG_DIR/config.json.new"
FILES_STAGING="$CONFIG_DIR/staging-files"
LOG_DIR="$HOME/Library/Logs/im-bridge"
LOG_FILE="$LOG_DIR/bridge.log"
LOG_MAX_BYTES=10485760
LOG_FILE_COUNT=5
PLIST="$HOME/Library/LaunchAgents/dev.im-bridge.bridge.plist"
LABEL="dev.im-bridge.bridge"
DOMAIN="gui/$(id -u)"
# Non-secret answers only, so a re-run can offer them again. The bot token is
# never written here; it goes straight from the hidden prompt into the config.
ENV_FILE="$CONFIG_DIR/wizard-values"
BACKUP_DIR=""
SERVICE_WAS_LOADED=0
SERVICE_STOPPED=0
CONFIG_REPLACED=0
PLIST_REPLACED=0
TRANSACTION_STARTED=0

rollback() {
  local status=$?
  (( status == 0 || TRANSACTION_STARTED == 0 )) && return 0
  if (( SERVICE_STOPPED == 1 )); then
    launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true
  fi
  if (( CONFIG_REPLACED == 1 )); then
    if [[ -n "$BACKUP_DIR" && -f "$BACKUP_DIR/config.json" ]]; then
      cp "$BACKUP_DIR/config.json" "$CONFIG_FILE"
      chmod 600 "$CONFIG_FILE"
    else
      rm -f "$CONFIG_FILE"
    fi
  fi
  if (( PLIST_REPLACED == 1 )); then
    if [[ -n "$BACKUP_DIR" && -f "$BACKUP_DIR/bridge.plist" ]]; then
      cp "$BACKUP_DIR/bridge.plist" "$PLIST"
    else
      rm -f "$PLIST"
    fi
  fi
  if (( SERVICE_STOPPED == 1 && SERVICE_WAS_LOADED == 1 )) && [[ -f "$PLIST" ]]; then
    launchctl bootstrap "$DOMAIN" "$PLIST" || warn "failed to restore the previous LaunchAgent; run setup again"
  fi
  # Staged files this run created but never moved into place.
  [[ -z "${CONFIG_WRITER_RESERVED:-}" ]] || rm -f "$CONFIG_WRITER_RESERVED"
  [[ -z "${CONFIG_WRITER_TMP:-}" ]] || rm -f "$CONFIG_WRITER_TMP"
  [[ -z "${PLIST_TMP:-}" ]] || rm -f "$PLIST_TMP"
  rm -f "$CONFIG_TMP"
  rm -rf "$FILES_STAGING"
  [[ -z "$BACKUP_DIR" ]] || rm -rf "$BACKUP_DIR"
  # The bridge log survives rollback on purpose: it is the only record of why a
  # start attempt failed, and the log has no field that can hold the token.
  warn "setup failed; previous configuration, service files, and service were restored when available"
  [[ ! -f "$LOG_FILE" ]] || note "bridge log kept for diagnosis: $LOG_FILE"
}
trap rollback EXIT

stage "Pre-flight checks"
say "This verifies local requirements without reading or printing your bot token."
[[ "$(uname -s)" == "Darwin" ]] || { warn "this wizard requires macOS"; exit 1; }
[[ -t 0 ]] || { warn "run this wizard from an interactive terminal"; exit 1; }
for command in node pnpm launchctl plutil stat; do
  command -v "$command" >/dev/null 2>&1 || { warn "$command is missing"; exit 1; }
done
NODE_BIN=$(command -v node)
NODE_DIR=$(dirname "$NODE_BIN")
NODE_MAJOR=$("$NODE_BIN" -p 'Number(process.versions.node.split(".")[0])')
(( NODE_MAJOR >= 24 )) || { warn "Node.js 24 or newer is required"; exit 1; }
[[ "$(pnpm --version)" == "11.21.0" ]] || { warn "pnpm 11.21.0 is required by this repository"; exit 1; }
[[ -f "$BRIDGE_ENTRY" ]] || { warn "$BRIDGE_ENTRY is missing; run this script from its checkout"; exit 1; }
say "Installing the pinned dependency tree of this checkout."
( cd "$PROJECT_DIR" && pnpm i --frozen-lockfile )
mkdir -p "$CONFIG_DIR" "$LOG_DIR" "$HOME/Library/LaunchAgents"
chmod 700 "$CONFIG_DIR"
if launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1; then
  SERVICE_WAS_LOADED=1
  note "An existing $LABEL is loaded. It keeps running until every check below passes."
fi
note "Node $("$NODE_BIN" --version), pnpm $(pnpm --version), runtime $BRIDGE_DIR."
pause "Pre-flight checks passed. Press Enter to continue."

stage "Collect configuration"
say "The token is read with the terminal echo disabled and is never printed, logged, or stored anywhere but the 600-mode config file."
ask_secret BOT_TOKEN "Telegram bot token:"
[[ "$BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]{35,}$ ]] || {
  warn "that is not a Telegram bot token (expected <bot id>:<secret>)"
  exit 1
}
ask ALLOWED_USER_IDS "Allowed Telegram user ids, comma separated:"
[[ "$ALLOWED_USER_IDS" =~ ^[0-9]+(,[[:space:]]*[0-9]+)*$ ]] || {
  warn "the allowlist must be one or more numeric user ids; it is the only authentication the bridge has"
  exit 1
}
ask CWD_ALIASES "cwd aliases as name=/absolute/path, comma separated:"
[[ "$CWD_ALIASES" =~ ^[A-Za-z0-9_-]{1,32}=/[^,]*(,[[:space:]]*[A-Za-z0-9_-]{1,32}=/[^,]*)*$ ]] || {
  warn "every alias must be name=/absolute/path"
  exit 1
}
ask DATABASE_PATH "SQLite database path [$HOME/.local/share/im-bridge/bridge.db]:"
[[ -n "$DATABASE_PATH" ]] || DATABASE_PATH="$HOME/.local/share/im-bridge/bridge.db"
[[ "$DATABASE_PATH" == /* ]] || { warn "the database path must be absolute"; exit 1; }
ask DSH_URL "dsh base URL [http://127.0.0.1:3080]:"
[[ -n "$DSH_URL" ]] || DSH_URL="http://127.0.0.1:3080"
[[ "$DSH_URL" =~ ^https?://[^[:space:]]+$ ]] || { warn "the dsh URL must be an absolute http URL"; exit 1; }
ask LOG_LEVEL "Log level, info or debug [info]:"
[[ -n "$LOG_LEVEL" ]] || LOG_LEVEL="info"
[[ "$LOG_LEVEL" == "info" || "$LOG_LEVEL" == "debug" ]] || { warn "the log level must be info or debug"; exit 1; }
mkdir -p "$(dirname "$DATABASE_PATH")"
# Non-secret answers only. A re-run offers them again; the token is asked for
# every time, because there is no safe place to keep it outside the config.
write_env ALLOWED_USER_IDS "$ALLOWED_USER_IDS"
write_env CWD_ALIASES "$CWD_ALIASES"
write_env DATABASE_PATH "$DATABASE_PATH"
write_env DSH_URL "$DSH_URL"
write_env LOG_LEVEL "$LOG_LEVEL"
chmod 600 "$ENV_FILE"
note "Collected the allowlist, the aliases, the database path, the dsh URL, and the log level."
pause "Configuration collected. Press Enter to write it."

stage "Write and validate the configuration"
say "The file is written to a staging path, validated by the bridge's own loader, and only then moved into place."
rm -rf "$FILES_STAGING"
mkdir -m 700 "$FILES_STAGING"
TRANSACTION_STARTED=1
# Node 24 selects the module loader from the final extension, so the temp file
# must still end in .mjs or --check fails with ERR_UNKNOWN_FILE_EXTENSION. BSD
# mktemp only expands XXXXXX at the end of a template, so claim the name
# exclusively first, then move it back under the .mjs extension.
CONFIG_WRITER_RESERVED=$(mktemp "$FILES_STAGING/write-config.XXXXXX")
CONFIG_WRITER_TMP="${CONFIG_WRITER_RESERVED}.mjs"
mv "$CONFIG_WRITER_RESERVED" "$CONFIG_WRITER_TMP"
# Quoted heredoc: nothing here is interpolated by the shell. The token arrives
# on standard input and every other value through the environment, so neither
# reaches a command line, a process listing, or this file.
cat > "$CONFIG_WRITER_TMP" <<"WRITER_EOF"
import { readFileSync, writeFileSync } from "node:fs";

function required(name) {
  const value = process.env[name];
  if (value === undefined || value.trim() === "") throw new Error(name + " is empty");
  return value;
}

const token = readFileSync(0, "utf8").trim();
if (!/^[0-9]+:[A-Za-z0-9_-]{35,}$/.test(token)) {
  // The value is never quoted back: this message reaches a terminal.
  throw new Error("bot token is not in the <bot id>:<secret> shape");
}

const allowedUserIds = required("BRIDGE_ALLOWLIST")
  .split(",")
  .map(entry => Number(entry.trim()));
if (allowedUserIds.length === 0 || !allowedUserIds.every(Number.isSafeInteger)) {
  throw new Error("the allowlist must be one or more numeric user ids");
}

const cwdAliases = {};
for (const entry of required("BRIDGE_ALIASES").split(",")) {
  const at = entry.indexOf("=");
  if (at < 0) throw new Error("every cwd alias must be name=/absolute/path");
  const alias = entry.slice(0, at).trim();
  const directory = entry.slice(at + 1).trim();
  if (!/^[A-Za-z0-9_-]{1,32}$/.test(alias)) throw new Error("invalid cwd alias name: " + alias);
  if (!directory.startsWith("/")) throw new Error("cwd alias " + alias + " needs an absolute path");
  cwdAliases[alias] = directory;
}

const document = {
  botToken: token,
  allowedUserIds,
  cwdAliases,
  databasePath: required("BRIDGE_DATABASE"),
  dshUrl: required("BRIDGE_DSH_URL"),
  logLevel: required("BRIDGE_LOG_LEVEL"),
};
writeFileSync(required("BRIDGE_CONFIG_OUT"), JSON.stringify(document, null, 2) + "\n", { mode: 0o600 });
WRITER_EOF
chmod 700 "$CONFIG_WRITER_TMP"
"$NODE_BIN" --check "$CONFIG_WRITER_TMP"
rm -f "$CONFIG_TMP"
# umask 077 covers the window between creation and the explicit chmod.
( umask 077
  printf '%s' "$BOT_TOKEN" | BRIDGE_ALLOWLIST="$ALLOWED_USER_IDS" \
    BRIDGE_ALIASES="$CWD_ALIASES" \
    BRIDGE_DATABASE="$DATABASE_PATH" \
    BRIDGE_DSH_URL="$DSH_URL" \
    BRIDGE_LOG_LEVEL="$LOG_LEVEL" \
    BRIDGE_CONFIG_OUT="$CONFIG_TMP" \
    "$NODE_BIN" "$CONFIG_WRITER_TMP" )
chmod 600 "$CONFIG_TMP"
[[ "$(stat -f '%Lp' "$CONFIG_TMP")" == "600" ]] || { warn "the staged config did not get mode 600"; exit 1; }
[[ "$(stat -f '%u' "$CONFIG_TMP")" == "$(id -u)" ]] || { warn "the staged config is not owned by this user"; exit 1; }
# The loader is the authority on every field, so the wizard never re-implements
# it: this is the same code the service runs at startup.
"$NODE_BIN" --experimental-strip-types "$BRIDGE_ENTRY" "$CONFIG_TMP" config check
BACKUP_DIR=$(mktemp -d)
[[ ! -f "$CONFIG_FILE" ]] || cp "$CONFIG_FILE" "$BACKUP_DIR/config.json"
[[ ! -f "$PLIST" ]] || cp "$PLIST" "$BACKUP_DIR/bridge.plist"
mv "$CONFIG_TMP" "$CONFIG_FILE"
CONFIG_REPLACED=1
"$NODE_BIN" --experimental-strip-types "$BRIDGE_ENTRY" "$CONFIG_FILE" config check
rm -f "$CONFIG_WRITER_TMP"
note "Wrote a 600-mode configuration owned by this user and validated it with the bridge loader."
pause "Configuration validated. Press Enter to run the test suite."

stage "Run typecheck and the test suite"
say "The service must not be installed from a checkout that does not typecheck or pass its tests."
( cd "$PROJECT_DIR" && pnpm -F bridge typecheck )
( cd "$PROJECT_DIR" && pnpm -F bridge test )
note "Typecheck and the complete unit and integration suite passed."
pause "Tests passed. Press Enter to prove Rich Messages against the real bot."

stage "Prove Rich Messages against the real Bot API"
say "Rich Message support is a deployment prerequisite: there is no plain-message fallback."
if (( SERVICE_WAS_LOADED == 1 )); then
  # Two pollers cannot share getUpdates, so the running service stands down for
  # the probe. Rollback restores it with the previous plist.
  launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true
  SERVICE_STOPPED=1
  note "Stopped the running $LABEL so the probe owns long polling."
fi
step "In the private chat with the bot, create a dedicated topic for this check."
step "Send any message inside that topic; the ids are read from that message."
# tee keeps the wait visible: detection blocks until the human posts, and the
# evidence lines are the only sign of progress. pipefail keeps node's failure.
DETECT_OUTPUT=$("$NODE_BIN" --experimental-strip-types "$BRIDGE_ENTRY" "$CONFIG_FILE" topic detect | tee /dev/tty)
TEST_THREAD_ID=$(printf '%s\n' "$DETECT_OUTPUT" | sed -n 's/.*"event":"bridge.topic.detected".*"threadId":\([0-9-]*\).*/\1/p' | tail -n1)
TEST_CHAT_ID=$(printf '%s\n' "$DETECT_OUTPUT" | sed -n 's/.*"event":"bridge.topic.detected".*"chatId":\([0-9-]*\).*/\1/p' | tail -n1)
[[ -n "$TEST_THREAD_ID" && -n "$TEST_CHAT_ID" ]] || { warn "no private topic was detected"; exit 1; }
note "Detected test topic $TEST_THREAD_ID."
# getMe proves the token and threaded mode; the probe then proves a structured
# draft with a thinking block and a final Rich Message in that same topic.
"$NODE_BIN" --experimental-strip-types "$BRIDGE_ENTRY" "$CONFIG_FILE" probe \
  --thread "$TEST_THREAD_ID" --chat "$TEST_CHAT_ID"
note "getMe, threaded mode, sendRichMessageDraft blocks, and sendRichMessage all verified."
pause "Rich Message support proved. Press Enter to run the live end-to-end check."

stage "Run the live end-to-end check"
say "This drives the real bridge against the real Telegram bot and the real dsh, in a temporary database."
say "It prints the steps you have to take in Telegram and waits for each one."
note "It spends a small number of real DeepSeek turns and asks you to answer two approvals."
confirm "Run the live end-to-end check now?" || exit 1
( cd "$PROJECT_DIR" && pnpm -F bridge live:e2e "$CONFIG_FILE" --thread "$TEST_THREAD_ID" --chat "$TEST_CHAT_ID" )
note "Every live checklist item passed."
pause "Live check passed. Press Enter to install the service."

stage "Install and verify the LaunchAgent"
say "The agent starts at login and restarts only after an abnormal exit, so a deliberate stop stays stopped."
rotate_logs() {
  local index
  if [[ ! -f "$LOG_FILE" ]]; then return 0; fi
  if (( $(stat -f '%z' "$LOG_FILE") < LOG_MAX_BYTES )); then return 0; fi
  rm -f "$LOG_FILE.$(( LOG_FILE_COUNT - 1 ))"
  for (( index = LOG_FILE_COUNT - 2; index >= 1; index-- )); do
    if [[ -f "$LOG_FILE.$index" ]]; then mv "$LOG_FILE.$index" "$LOG_FILE.$(( index + 1 ))"; fi
  done
  mv "$LOG_FILE" "$LOG_FILE.1"
}
rotate_logs
PLIST_TMP="$FILES_STAGING/bridge.plist"
cat > "$PLIST_TMP" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$NODE_BIN</string>
    <string>--experimental-strip-types</string>
    <string>$BRIDGE_ENTRY</string>
    <string>$CONFIG_FILE</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>$LOG_FILE</string>
  <key>StandardErrorPath</key>
  <string>$LOG_FILE</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>$NODE_DIR:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
</dict>
</plist>
EOF
chmod 600 "$PLIST_TMP"
plutil -lint "$PLIST_TMP" >/dev/null
if (( SERVICE_STOPPED == 0 )); then
  launchctl bootout "$DOMAIN/$LABEL" >/dev/null 2>&1 || true
  SERVICE_STOPPED=1
fi
mv "$PLIST_TMP" "$PLIST"
PLIST_REPLACED=1
launchctl bootstrap "$DOMAIN" "$PLIST"
launchctl kickstart -k "$DOMAIN/$LABEL"
# The service reports itself started in its own log; nothing else proves that
# the config, the token, and threaded mode all still work under launchd.
STARTED=0
for _ in {1..30}; do
  if [[ -f "$LOG_FILE" ]] && grep -q '"event":"bridge.started"' "$LOG_FILE"; then STARTED=1; break; fi
  sleep 1
done
# The token never reaches the log, but a tail is still shown through a redactor
# and only for lines that match known-safe diagnostic shapes. Anything else is
# left in the file rather than printed.
show_log_tail() {
  [[ -f "$LOG_FILE" ]] || { warn "no bridge log exists at $LOG_FILE"; return 0; }
  if grep -q 'threaded mode' "$LOG_FILE"; then
    note "diagnosis: the bot reports threaded mode disabled"
  elif grep -q '^Config ' "$LOG_FILE"; then
    note "diagnosis: the configuration file was rejected at startup"
  elif grep -q '"event":"telegram.poll.failed"' "$LOG_FILE"; then
    note "diagnosis: long polling could not reach the Bot API"
  elif grep -q '"event":"bridge.started"' "$LOG_FILE"; then
    note "diagnosis: the bridge reported a successful start"
  else
    note "diagnosis: no recognized startup signature"
  fi
  note "full bridge log kept at $LOG_FILE"
}
(( STARTED == 1 )) || {
  warn "the LaunchAgent did not report bridge.started within 30 seconds"
  show_log_tail
  exit 1
}
launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1 || {
  warn "the LaunchAgent is not loaded after bootstrap"
  show_log_tail
  exit 1
}
CONFIG_REPLACED=0
PLIST_REPLACED=0
SERVICE_STOPPED=0
TRANSACTION_STARTED=0
rm -rf "$BACKUP_DIR" "$FILES_STAGING"
trap - EXIT
note "LaunchAgent $LABEL is loaded, reported bridge.started, and will start at the next user login."
note "Logs are JSON Lines at $LOG_FILE, rotated to $LOG_FILE_COUNT files of $LOG_MAX_BYTES bytes on each setup run."
finish
